# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: auntmays
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: mail
# "service" is the name of this project. This will also be added to your AWS resource names.
service: sendEmail

provider:
  name: aws
  runtime: python3.12
  # Uncomment to easily set up a custom domain. Read the docs for more details:
  # https://www.serverless.com/framework/docs/providers/aws/guide/domains
  # domain: api.example.com

  environment:
    EMAIL: ${env:EMAIL}
    EMAIL_PASSWORD: ${env:EMAIL_PASSWORD}

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

functions:
  sendEmail:
    handler: handler.send_email
    events:
      - http:
          path: send-email
          method: post